#!/usr/bin/env bash

set -euo pipefail

root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
config_file="$root_dir/config.sh"
sample_config="$root_dir/sample_config.sh"

configure() {
  local DCC_HOST DCC_PORT host_input port_input

  # Reuse the documented defaults and any environment overrides as prompt
  # defaults without allowing them to leak out of this function.
  source "$sample_config"

  while true; do
    read -r -p "Listen address [$DCC_HOST]: " host_input
    host_input="${host_input:-$DCC_HOST}"
    if [[ "$host_input" =~ ^[A-Za-z0-9._:-]+$ ]]; then
      break
    fi
    printf 'Enter an IPv4, IPv6, or host name.\n' >&2
  done

  while true; do
    read -r -p "Port [$DCC_PORT]: " port_input
    port_input="${port_input:-$DCC_PORT}"
    if [[ "$port_input" =~ ^[0-9]{1,5}$ ]] && ((10#$port_input >= 1 && 10#$port_input <= 65535)); then
      break
    fi
    printf 'Enter a port from 1 to 65535.\n' >&2
  done

  {
    printf '# Generated by ./start.sh --configure. This file is not tracked by Git.\n'
    printf 'export DCC_HOST="${DCC_HOST:-%s}"\n' "$host_input"
    printf 'export DCC_PORT="${DCC_PORT:-%s}"\n' "$port_input"
  } > "$config_file"
  printf 'Wrote %s\n' "$config_file"
}

case "${1:-}" in
  --configure)
    if (($# != 1)); then
      printf 'Usage: %s [--configure]\n' "$0" >&2
      exit 2
    fi
    configure
    ;;
  '')
    ;;
  *)
    printf 'Usage: %s [--configure]\n' "$0" >&2
    exit 2
    ;;
esac

if [[ ! -f "$config_file" && -t 0 ]]; then
  read -r -p 'Create a local config.sh now? [y/N] ' create_config
  if [[ "$create_config" =~ ^[Yy]$ ]]; then
    configure
  fi
fi

if [[ -f "$config_file" ]]; then
  # Keep explicit process environment values ahead of config.sh defaults.
  source "$config_file"
fi

cd "$root_dir"
exec npm start
